services:
  - type: web
    name: stylish-name-bot
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python stylish_name_bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
    healthCheckPath: /
    autoDeploy: true 