services:
  - type: web
    name: fontbo
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python stylish_name_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.1
    autoDeploy: true
    minInstances: 1
    maxInstances: 1
    healthCheckPath: /
    healthCheckTimeout: 5
    preDeployCommand: echo "Stopping previous deployment before starting new one..."
    sleepApplication: false 